version: "3.8"

services:
  nginx-proxy:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - chat_app_network

  frontend:
    build: ./public
    env_file:
      - ./public/.env
    depends_on:
      - api
    networks:
      - chat_app_network

  api:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - chat_app_network

  mongo:
    image: mongodb/mongodb-community-server:7.0.23-ubi9
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat_app_network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    depends_on:
      - mongo
    networks:
      - chat_app_network

volumes:
  mongodb_data:

networks:
  chat_app_network:
    driver: bridge
    name: chat_app_network
